server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
 datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mysql://localhost:3307/board_db?serverTimezone=Asia/Seoul
  username: moonsoo
  password: cos1234
 jpa:
  open-in-view: true
  hibernate:
    ddl-auto: update
    naming:
     physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    use-new-id-generator-mappings: false
  show-sql: true
  properties:
    hibernate.format_sql: true

    

